Repository imi-frankfurt/dataelementhub.rest, pull requests merged in 2022-05, with the labels that each got.

#49 #14 - Element relations error
  src/main/java/de/dataelementhub/rest/controller/v1/ElementRelationController.java
  src/main/resources/static/api-docs.json
Labels: bug, needs review

#55 #54 - Update dependencies
  pom.xml
  src/main/java/de/dataelementhub/rest/DataElementHubRestApplication.java
  src/main/java/de/dataelementhub/rest/configuration/AsyncConfig.java
  src/main/java/de/dataelementhub/rest/configuration/Config.java
  src/main/java/de/dataelementhub/rest/configuration/KeycloakRealmRoleConverter.java
  src/main/java/de/dataelementhub/rest/configuration/OpenApiConfig.java
  src/main/java/de/dataelementhub/rest/configuration/SecurityConfig.java
  src/main/java/de/dataelementhub/rest/controller/v1/ApiVersion.java
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ElementRelationController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ExportController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ImportController.java
  src/main/java/de/dataelementhub/rest/controller/v1/NamespaceController.java
  src/main/java/de/dataelementhub/rest/controller/v1/SearchController.java
  src/main/java/de/dataelementhub/rest/controller/v1/SourceController.java
  src/main/java/de/dataelementhub/rest/controller/v1/TreeController.java
  src/main/java/de/dataelementhub/rest/controller/v1/VersionController.java
  src/main/java/de/dataelementhub/rest/dto/tree/AttributesList.java
  src/main/java/de/dataelementhub/rest/dto/tree/Itree.java
  src/main/java/de/dataelementhub/rest/dto/tree/State.java
  src/main/java/de/dataelementhub/rest/dto/tree/TreeNode.java
Labels: critical, needs review, refactoring

#47 #46 - Reconstruct export output and import input
  src/main/java/de/dataelementhub/rest/controller/v1/ExportController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ImportController.java
  src/main/resources/schema/StagingImport.json
  src/main/resources/schema/StagingImport.xsd
Labels: needs review, refactoring

#51 #50 - Improve performance
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ElementRelationController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ExportController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ImportController.java
  src/main/java/de/dataelementhub/rest/controller/v1/NamespaceController.java
  src/main/java/de/dataelementhub/rest/controller/v1/SearchController.java
  src/main/java/de/dataelementhub/rest/controller/v1/SourceController.java
Labels: needs review, refactoring

#53 #52 - enable calling path for public elements without login
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
  src/main/java/de/dataelementhub/rest/controller/v1/ExportController.java
Labels: feature, needs review
