Repository imi-frankfurt/dataelementhub.rest, pull requests merged in 2022-06, with the labels that each got.

#62 #61 - Update Members should return 204 on success
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
Labels: bug, needs review, nice to have

#66 #65 - Remove catch blocks from get element paths method
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
Labels: needs review, refactoring

#70 #68 - Creating a dataElement with valueDomainUrn that does not exist …
  src/main/java/de/dataelementhub/rest/controller/v1/ElementController.java
Labels: bug, needs review
